version: '3'
services:
  postgresDB:
    container_name: postgresDB
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgresDB:/var/lib/postgresql/data
      - ./conf/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  marketplace-goapi:
    build: 
      context: .
      dockerfile: dockerfile.dev
    container_name: marketplace-goapi
    ports:
      - "5500:5500"
    volumes:
      - .:/app
    depends_on:
      postgresDB:
        condition: service_healthy

volumes:
  postgresDB:
    driver: local

